# This workflow is triggered by the parent workflow and deploys the required solutions to the specified environment
# The solutions are deployed in sequential order one at a time
name: _Deploy Environment

permissions:
  id-token: write
  packages: write
  contents: write

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stageAndUpgrade:
          required: false
          type: string # workflow calls use strings instead of booleans
          default: 'true'
jobs:
  Deploy:
      strategy:
        max-parallel: 1
        matrix:
          include:
            - targetName: core
              solutionName: ContosoRealEstateCustomControls
            - targetName: core
              solutionName: ContosoRealEstateCore
            - targetName: portal
              solutionName: ContosoRealEstateCustomControls
            - targetName: portal
              solutionName: ContosoRealEstateCore
            - targetName: portal
              solutionName: ContosoRealEstatePortal
    
      uses: ./.github/workflows/import-solution.yml
      with:
          environment: ${{ inputs.environment}}
          solutionName: ${{ matrix.solutionName }}
          targetName: ${{ matrix.targetName }}
          stageAndUpgrade: ${{ inputs.stageAndUpgrade }}
      
      
